### ISSUE TITLE
i5-9600k Asus-Prime-Z370-P rx590 can use this EFI?

### ISSUE THREAD

**Issue by micenote** [DmitriyyyyS/Asus-Prime-Z370-P#1]
i5-9600k Asus-Prime-Z370-P rx590 can use this EFI?

**Comment by DmitriyyyyS** [comment]
Yes, EFI is compatible.

**Comment by micenote** [comment]
thank you.Let me try!

**Comment by micenote** [comment]
Use your efi, after boot is Russian, how to modify to other languages?
