### ISSUE TITLE
How to monitor GPU temperature?

### ISSUE THREAD

**Issue by shadow3g** [DmitriyyyyS/Asus-Prime-Z370-P#10]
Could you please add the solution how to monitor GPU temperature?

**Comment by DmitriyyyyS** [comment]
For this you need to install the HWmonitor program

**Comment by shadow3g** [comment]
> For this you need to install the HWmonitor program

HWmonitor was installed but it just only shows CPU and hard drive temp. The GPU temp didn't show.
<img width="248" alt="HWmonitor" src="https://user-images.githubusercontent.com/12130283/109408658-4e181100-7940-11eb-8881-698bef51c2db.png">

Did your computer show GPU temp?

**Comment by DmitriyyyyS** [comment]
1e, you did not install Hwmonitor here, you need the one that was made under VirtualSMC, then there will be a display, 2e, if you have a graphics processor, this is an Intel GPU, then there will be no special information.

**Comment by shadow3g** [comment]
> 1e, you did not install Hwmonitor here, you need the one that was made under VirtualSMC, then there will be a display, 2e, if you have a graphics processor, this is an Intel GPU, then there will be no special information.

Could you please give me the link to Hwmonitor that was made under VirtualSMC?
You will see I had GPU RX580 in macinfo as the picture that I capture from my Hackintosh.
<img width="890" alt="macInfo" src="https://user-images.githubusercontent.com/12130283/109425786-f2c93b80-799e-11eb-98ae-2a424fde9805.png">

**Comment by DmitriyyyyS** [comment]
https://github.com/CloverHackyColor/HWMonitorSMC2/releases/tag/v2.6.1

**Comment by DmitriyyyyS** [comment]
You need to start, in the settings enable the run mode after the system starts, and restart the computer

**Comment by shadow3g** [comment]
> You need to start, in the settings enable the run mode after the system starts, and restart the computer

It is working now. Thank you very much.
<img width="382" alt="GPUinfo" src="https://user-images.githubusercontent.com/12130283/109426489-bf88ab80-79a2-11eb-95e8-714fa0eeb436.png">

**Comment by DmitriyyyyS** [comment]
The problem was solved, I close the topic.
