### ISSUE TITLE
It was perfect, but one problem was that the core graphics card wasn't being driven

### ISSUE THREAD

**Issue by micenote** [DmitriyyyyS/Asus-Prime-Z370-P#2]
It was perfect, but one problem was that the core graphics card wasn't being driven
<img width="863" alt="截屏2020-04-22 下午7 48 53" src="https://user-images.githubusercontent.com/13486634/79978348-5b6ba000-84d2-11ea-9599-a224319e66b8.png">
My CPU is i5-9600k,Video Adapter Intel(R) UHD Graphics 630
is opened Intel(R) UHD Graphics 630 in BIOS yet

**Comment by micenote** [comment]
in BIOS is opened Intel(R) UHD Graphics 630

**Comment by DmitriyyyyS** [comment]
For Intel GPU (IQSV) in the BIOS, you need to enable Intel graphics, with the lowest available memory value (DVMT), 32 MB is recommended, if the (DVMT) setting is not available, leave it by default (Enabled). Intel (IQSV) works as an acceleration, and does not appear in the graphics settings.

**Comment by micenote** [comment]
> For Intel GPU (IQSV) in the BIOS, you need to enable Intel graphics, with the lowest available memory value (DVMT), 32 MB is recommended, if the (DVMT) setting is not available, leave it by default (Enabled). Intel (IQSV) works as an acceleration, and does not appear in the graphics settings.

Thank you very much,According to your description,I think Intel GPU is worked.
