### ISSUE TITLE
Any issue with Sleep in Catalina?

### ISSUE THREAD

**Issue by kho-umam** [DmitriyyyyS/Asus-Prime-Z370-P#6]
Im planning to buy z370-p II, i7-8700, MSI RX570 Armor.
But I've seen some repo with sleep issue on this motherboard with Catalina.

**Comment by DmitriyyyyS** [comment]
Yes, I tested it, the dream worked, the main thing is that the BIOS should be correctly configured, and assemblies would not be used, but a clean operating system
